// import PortfolioService from '@/services/PortfolioService.js'

const path = "images/portfolio/"
const portfolio= [
    {
      id: '1',
      mode: "tuto",
      url: 'travelagency-mod.netlify.app',
      img: path+'voyage.png',
      banner: path+'voyage.png',
      mod: 'voyage',
      slug: 'travel-agency',
      alt: 'travel agency',
      name: 'Travel Agency',
      desc: 'Premier site en HTML / CSS',
      tuto: true,
    },
    {
      id: '2',
      mode: "tuto",
      type: "game",
      url: 'snakeey.netlify.app',
      img: path+'serpent.png',
      banner: path+'serpent.png',
      slug: 'snakeey',
      mod: 'snakeey',
      alt: 'snakeey',
      name: 'Snakeey',
      desc: 'Version JS de Snake',
      tuto: true,
    },
    {
      id: '3',
      mode: "tuto",
      url: 'topactrices.netlify.app',
      img: path+'actrices.png',
      banner: path+'color-image.jpg',
      alt: 'top 5 actrices',
      mod: 'actrices',
      slug: 'actrices',
      name: 'Top 5 Actrices',
      desc: 'Site en jQuery',
      tuto: true,
    },
    {
      id: '4',
      mode: "tuto",
      url: 'do-pe.netlify.app',
      img: path+'banner-overlay1.png',
      banner: path+'banner-overlay1.png',
      alt: 'do-pe',
      mod: 'dope',
      slug: 'dope',
      name: 'Do-Pe',
      tuto: true,
      desc: 'Site en VueJS 2',
    },
    
    {
      id: '5',
      mode: "self",
      type: "blog",
      url: 'pklinux.netlify.app',
      img: path+'pklinux.png',
      banner: path+'pklinux.png',
      alt: 'pklinux',
      mod: 'pklinux',
      slug: 'pklinux',
      name: 'PKLinux',
      desc: 'Site dédié à GNU/Linux',
    },
    {
      id: '6',
      mode: "self",
      type:"game",
      url: 'rick-morty-game.netlify.app',
      img: path+'rick-morty.png',
      banner: path+'rick-morty.png',
      alt: 'rick-morty',
      mod: 'rick-morty',
      slug: 'rick-morty',
      name: 'rick-morty',
      desc: 'Jeu de marteau sur le thème de Rick & Morty',
    },
    {
      id: '7',
      mode: "self",
      type:"streaming",
      url: 'magicmusic.netlify.app',
      img: path+'magic-music.png',
      banner: path+'magic-music.png',
      alt: 'magic-music',
      mod: 'magic-music',
      slug: 'magic-music',
      name: 'magic-music',
      desc: 'Sélecteur d\'artistes',
    },
    {
      id: '8',
      mode: "self",
      type:"drumkit",
      url: 'beatapp.netlify.app',
      img: path+'beat-app.png',
      banner: path+'beat-app.png',
      alt: 'beat-app',
      mod: 'beat-app',
      slug: 'beat-app',
      name: 'beat-app',
      desc: 'Séquenceur de percussions',
    },
    {
      id: '9',
      mode: "self",
      type:"games",
      url: 'familygames.netlify.app',
      img: path+'family.png',
      banner: path+'family.png',
      alt: 'family',
      mod: 'family',
      slug: 'family',
      name: 'family',
      desc: 'Jeux familiaux',
    },
    {
      id: '10',
      mode: "self",
      type:"dating",
      url: 'findy.netlify.app',
      img: path+'findy.png',
      banner: path+'findy.png',
      alt: 'findy',
      mod: 'findy',
      slug: 'findy',
      name: 'findy',
      desc: 'Dating Coach',
    },
    
  ]

  export {portfolio}
